// Generated by ProtoGen, Version=2.3.0.277, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace bnet.protocol.notification {
  
  namespace Proto {
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
    public static partial class Notification {
    
      #region Extension registration
      public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
      }
      #endregion
      #region Static variables
      internal static pbd::MessageDescriptor internal__static_bnet_protocol_notification_Notification__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::bnet.protocol.notification.Notification, global::bnet.protocol.notification.Notification.Builder> internal__static_bnet_protocol_notification_Notification__FieldAccessorTable;
      internal static pbd::MessageDescriptor internal__static_bnet_protocol_notification_FindClientRequest__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::bnet.protocol.notification.FindClientRequest, global::bnet.protocol.notification.FindClientRequest.Builder> internal__static_bnet_protocol_notification_FindClientRequest__FieldAccessorTable;
      internal static pbd::MessageDescriptor internal__static_bnet_protocol_notification_FindClientResponse__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::bnet.protocol.notification.FindClientResponse, global::bnet.protocol.notification.FindClientResponse.Builder> internal__static_bnet_protocol_notification_FindClientResponse__FieldAccessorTable;
      internal static pbd::MessageDescriptor internal__static_bnet_protocol_notification_RegisterClientRequest__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::bnet.protocol.notification.RegisterClientRequest, global::bnet.protocol.notification.RegisterClientRequest.Builder> internal__static_bnet_protocol_notification_RegisterClientRequest__FieldAccessorTable;
      internal static pbd::MessageDescriptor internal__static_bnet_protocol_notification_UnregisterClientRequest__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::bnet.protocol.notification.UnregisterClientRequest, global::bnet.protocol.notification.UnregisterClientRequest.Builder> internal__static_bnet_protocol_notification_UnregisterClientRequest__FieldAccessorTable;
      #endregion
      #region Descriptor
      public static pbd::FileDescriptor Descriptor {
        get { return descriptor; }
      }
      private static pbd::FileDescriptor descriptor;
      
      static Notification() {
        byte[] descriptorData = global::System.Convert.FromBase64String(
            "CidzZXJ2aWNlL25vdGlmaWNhdGlvbi9ub3RpZmljYXRpb24ucHJvdG8SGmJu" + 
            "ZXQucHJvdG9jb2wubm90aWZpY2F0aW9uGhxsaWIvcHJvdG9jb2wvYXR0cmli" + 
            "dXRlLnByb3RvGhlsaWIvcHJvdG9jb2wvZW50aXR5LnByb3RvGhFsaWIvcnBj" + 
            "L3JwYy5wcm90byLhAQoMTm90aWZpY2F0aW9uEioKCXNlbmRlcl9pZBgBIAEo" + 
            "CzIXLmJuZXQucHJvdG9jb2wuRW50aXR5SWQSNAoTc2VuZGVyX2dhbWVfYWNj" + 
            "b3VudBgCIAEoCzIXLmJuZXQucHJvdG9jb2wuRW50aXR5SWQSKgoJdGFyZ2V0" + 
            "X2lkGAMgAigLMhcuYm5ldC5wcm90b2NvbC5FbnRpdHlJZBIMCgR0eXBlGAQg" + 
            "AigJEjUKCWF0dHJpYnV0ZRgFIAMoCzIiLmJuZXQucHJvdG9jb2wuYXR0cmli" + 
            "dXRlLkF0dHJpYnV0ZSI/ChFGaW5kQ2xpZW50UmVxdWVzdBIqCgllbnRpdHlf" + 
            "aWQYASACKAsyFy5ibmV0LnByb3RvY29sLkVudGl0eUlkIlgKEkZpbmRDbGll" + 
            "bnRSZXNwb25zZRINCgVsYWJlbBgBIAIoDRIzChFjbGllbnRfcHJvY2Vzc19p" + 
            "ZBgCIAEoCzIYLmJuZXQucHJvdG9jb2wuUHJvY2Vzc0lkIkMKFVJlZ2lzdGVy" + 
            "Q2xpZW50UmVxdWVzdBIqCgllbnRpdHlfaWQYASACKAsyFy5ibmV0LnByb3Rv" + 
            "Y29sLkVudGl0eUlkIkUKF1VucmVnaXN0ZXJDbGllbnRSZXF1ZXN0EioKCWVu" + 
            "dGl0eV9pZBgBIAIoCzIXLmJuZXQucHJvdG9jb2wuRW50aXR5SWQykwMKE05v" + 
            "dGlmaWNhdGlvblNlcnZpY2USUwoQU2VuZE5vdGlmaWNhdGlvbhIoLmJuZXQu" + 
            "cHJvdG9jb2wubm90aWZpY2F0aW9uLk5vdGlmaWNhdGlvbhoVLmJuZXQucHJv" + 
            "dG9jb2wuTm9EYXRhEloKDlJlZ2lzdGVyQ2xpZW50EjEuYm5ldC5wcm90b2Nv" + 
            "bC5ub3RpZmljYXRpb24uUmVnaXN0ZXJDbGllbnRSZXF1ZXN0GhUuYm5ldC5w" + 
            "cm90b2NvbC5Ob0RhdGESXgoQVW5yZWdpc3RlckNsaWVudBIzLmJuZXQucHJv" + 
            "dG9jb2wubm90aWZpY2F0aW9uLlVucmVnaXN0ZXJDbGllbnRSZXF1ZXN0GhUu" + 
            "Ym5ldC5wcm90b2NvbC5Ob0RhdGESawoKRmluZENsaWVudBItLmJuZXQucHJv" + 
            "dG9jb2wubm90aWZpY2F0aW9uLkZpbmRDbGllbnRSZXF1ZXN0Gi4uYm5ldC5w" + 
            "cm90b2NvbC5ub3RpZmljYXRpb24uRmluZENsaWVudFJlc3BvbnNlMnYKFE5v" + 
            "dGlmaWNhdGlvbkxpc3RlbmVyEl4KFk9uTm90aWZpY2F0aW9uUmVjZWl2ZWQS" + 
            "KC5ibmV0LnByb3RvY29sLm5vdGlmaWNhdGlvbi5Ob3RpZmljYXRpb24aGi5i" + 
            "bmV0LnByb3RvY29sLk5PX1JFU1BPTlNF");
        pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
          descriptor = root;
          internal__static_bnet_protocol_notification_Notification__Descriptor = Descriptor.MessageTypes[0];
          internal__static_bnet_protocol_notification_Notification__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::bnet.protocol.notification.Notification, global::bnet.protocol.notification.Notification.Builder>(internal__static_bnet_protocol_notification_Notification__Descriptor,
                  new string[] { "SenderId", "SenderGameAccount", "TargetId", "Type", "Attribute", });
          internal__static_bnet_protocol_notification_FindClientRequest__Descriptor = Descriptor.MessageTypes[1];
          internal__static_bnet_protocol_notification_FindClientRequest__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::bnet.protocol.notification.FindClientRequest, global::bnet.protocol.notification.FindClientRequest.Builder>(internal__static_bnet_protocol_notification_FindClientRequest__Descriptor,
                  new string[] { "EntityId", });
          internal__static_bnet_protocol_notification_FindClientResponse__Descriptor = Descriptor.MessageTypes[2];
          internal__static_bnet_protocol_notification_FindClientResponse__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::bnet.protocol.notification.FindClientResponse, global::bnet.protocol.notification.FindClientResponse.Builder>(internal__static_bnet_protocol_notification_FindClientResponse__Descriptor,
                  new string[] { "Label", "ClientProcessId", });
          internal__static_bnet_protocol_notification_RegisterClientRequest__Descriptor = Descriptor.MessageTypes[3];
          internal__static_bnet_protocol_notification_RegisterClientRequest__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::bnet.protocol.notification.RegisterClientRequest, global::bnet.protocol.notification.RegisterClientRequest.Builder>(internal__static_bnet_protocol_notification_RegisterClientRequest__Descriptor,
                  new string[] { "EntityId", });
          internal__static_bnet_protocol_notification_UnregisterClientRequest__Descriptor = Descriptor.MessageTypes[4];
          internal__static_bnet_protocol_notification_UnregisterClientRequest__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::bnet.protocol.notification.UnregisterClientRequest, global::bnet.protocol.notification.UnregisterClientRequest.Builder>(internal__static_bnet_protocol_notification_UnregisterClientRequest__Descriptor,
                  new string[] { "EntityId", });
          return null;
        };
        pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
            new pbd::FileDescriptor[] {
            global::bnet.protocol.attribute.Proto.Attribute.Descriptor, 
            global::bnet.protocol.Entity.Descriptor, 
            global::bnet.protocol.Rpc.Descriptor, 
            }, assigner);
      }
      #endregion
      
    }
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
  public sealed partial class Notification : pb::GeneratedMessage<Notification, Notification.Builder> {
    private static readonly Notification defaultInstance = new Builder().BuildPartial();
    private static readonly string[] _notificationFieldNames = new string[] { "attribute", "sender_game_account", "sender_id", "target_id", "type" };
    private static readonly uint[] _notificationFieldTags = new uint[] { 42, 18, 10, 26, 34 };
    public static Notification DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override Notification DefaultInstanceForType {
      get { return defaultInstance; }
    }
    
    protected override Notification ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::bnet.protocol.notification.Proto.Notification.internal__static_bnet_protocol_notification_Notification__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<Notification, Notification.Builder> InternalFieldAccessors {
      get { return global::bnet.protocol.notification.Proto.Notification.internal__static_bnet_protocol_notification_Notification__FieldAccessorTable; }
    }
    
    public const int SenderIdFieldNumber = 1;
    private bool hasSenderId;
    private global::bnet.protocol.EntityId senderId_ = global::bnet.protocol.EntityId.DefaultInstance;
    public bool HasSenderId {
      get { return hasSenderId; }
    }
    public global::bnet.protocol.EntityId SenderId {
      get { return senderId_; }
    }
    
    public const int SenderGameAccountFieldNumber = 2;
    private bool hasSenderGameAccount;
    private global::bnet.protocol.EntityId senderGameAccount_ = global::bnet.protocol.EntityId.DefaultInstance;
    public bool HasSenderGameAccount {
      get { return hasSenderGameAccount; }
    }
    public global::bnet.protocol.EntityId SenderGameAccount {
      get { return senderGameAccount_; }
    }
    
    public const int TargetIdFieldNumber = 3;
    private bool hasTargetId;
    private global::bnet.protocol.EntityId targetId_ = global::bnet.protocol.EntityId.DefaultInstance;
    public bool HasTargetId {
      get { return hasTargetId; }
    }
    public global::bnet.protocol.EntityId TargetId {
      get { return targetId_; }
    }
    
    public const int TypeFieldNumber = 4;
    private bool hasType;
    private string type_ = "";
    public bool HasType {
      get { return hasType; }
    }
    public string Type {
      get { return type_; }
    }
    
    public const int AttributeFieldNumber = 5;
    private pbc::PopsicleList<global::bnet.protocol.attribute.Attribute> attribute_ = new pbc::PopsicleList<global::bnet.protocol.attribute.Attribute>();
    public scg::IList<global::bnet.protocol.attribute.Attribute> AttributeList {
      get { return attribute_; }
    }
    public int AttributeCount {
      get { return attribute_.Count; }
    }
    public global::bnet.protocol.attribute.Attribute GetAttribute(int index) {
      return attribute_[index];
    }
    
    public override bool IsInitialized {
      get {
        if (!hasTargetId) return false;
        if (!hasType) return false;
        if (HasSenderId) {
          if (!SenderId.IsInitialized) return false;
        }
        if (HasSenderGameAccount) {
          if (!SenderGameAccount.IsInitialized) return false;
        }
        if (!TargetId.IsInitialized) return false;
        foreach (global::bnet.protocol.attribute.Attribute element in AttributeList) {
          if (!element.IsInitialized) return false;
        }
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _notificationFieldNames;
      if (hasSenderId) {
        output.WriteMessage(1, field_names[2], SenderId);
      }
      if (hasSenderGameAccount) {
        output.WriteMessage(2, field_names[1], SenderGameAccount);
      }
      if (hasTargetId) {
        output.WriteMessage(3, field_names[3], TargetId);
      }
      if (hasType) {
        output.WriteString(4, field_names[4], Type);
      }
      if (attribute_.Count > 0) {
        output.WriteMessageArray(5, field_names[0], attribute_);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasSenderId) {
          size += pb::CodedOutputStream.ComputeMessageSize(1, SenderId);
        }
        if (hasSenderGameAccount) {
          size += pb::CodedOutputStream.ComputeMessageSize(2, SenderGameAccount);
        }
        if (hasTargetId) {
          size += pb::CodedOutputStream.ComputeMessageSize(3, TargetId);
        }
        if (hasType) {
          size += pb::CodedOutputStream.ComputeStringSize(4, Type);
        }
        foreach (global::bnet.protocol.attribute.Attribute element in AttributeList) {
          size += pb::CodedOutputStream.ComputeMessageSize(5, element);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static Notification ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static Notification ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static Notification ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static Notification ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static Notification ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static Notification ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static Notification ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static Notification ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static Notification ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static Notification ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(Notification prototype) {
      return (Builder) new Builder().MergeFrom(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
    public sealed partial class Builder : pb::GeneratedBuilder<Notification, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {}
      
      Notification result = new Notification();
      
      protected override Notification MessageBeingBuilt {
        get { return result; }
      }
      
      public override Builder Clear() {
        result = new Notification();
        return this;
      }
      
      public override Builder Clone() {
        return new Builder().MergeFrom(result);
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::bnet.protocol.notification.Notification.Descriptor; }
      }
      
      public override Notification DefaultInstanceForType {
        get { return global::bnet.protocol.notification.Notification.DefaultInstance; }
      }
      
      public override Notification BuildPartial() {
        if (result == null) {
          throw new global::System.InvalidOperationException("build() has already been called on this Builder");
        }
        result.attribute_.MakeReadOnly();
        Notification returnMe = result;
        result = null;
        return returnMe;
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is Notification) {
          return MergeFrom((Notification) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(Notification other) {
        if (other == global::bnet.protocol.notification.Notification.DefaultInstance) return this;
        if (other.HasSenderId) {
          MergeSenderId(other.SenderId);
        }
        if (other.HasSenderGameAccount) {
          MergeSenderGameAccount(other.SenderGameAccount);
        }
        if (other.HasTargetId) {
          MergeTargetId(other.TargetId);
        }
        if (other.HasType) {
          Type = other.Type;
        }
        if (other.attribute_.Count != 0) {
          base.AddRange(other.attribute_, result.attribute_);
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_notificationFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _notificationFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              global::bnet.protocol.EntityId.Builder subBuilder = global::bnet.protocol.EntityId.CreateBuilder();
              if (result.hasSenderId) {
                subBuilder.MergeFrom(SenderId);
              }
              input.ReadMessage(subBuilder, extensionRegistry);
              SenderId = subBuilder.BuildPartial();
              break;
            }
            case 18: {
              global::bnet.protocol.EntityId.Builder subBuilder = global::bnet.protocol.EntityId.CreateBuilder();
              if (result.hasSenderGameAccount) {
                subBuilder.MergeFrom(SenderGameAccount);
              }
              input.ReadMessage(subBuilder, extensionRegistry);
              SenderGameAccount = subBuilder.BuildPartial();
              break;
            }
            case 26: {
              global::bnet.protocol.EntityId.Builder subBuilder = global::bnet.protocol.EntityId.CreateBuilder();
              if (result.hasTargetId) {
                subBuilder.MergeFrom(TargetId);
              }
              input.ReadMessage(subBuilder, extensionRegistry);
              TargetId = subBuilder.BuildPartial();
              break;
            }
            case 34: {
              result.hasType = input.ReadString(ref result.type_);
              break;
            }
            case 42: {
              input.ReadMessageArray(tag, field_name, result.attribute_, global::bnet.protocol.attribute.Attribute.DefaultInstance, extensionRegistry);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasSenderId {
       get { return result.hasSenderId; }
      }
      public global::bnet.protocol.EntityId SenderId {
        get { return result.SenderId; }
        set { SetSenderId(value); }
      }
      public Builder SetSenderId(global::bnet.protocol.EntityId value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        result.hasSenderId = true;
        result.senderId_ = value;
        return this;
      }
      public Builder SetSenderId(global::bnet.protocol.EntityId.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        result.hasSenderId = true;
        result.senderId_ = builderForValue.Build();
        return this;
      }
      public Builder MergeSenderId(global::bnet.protocol.EntityId value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        if (result.hasSenderId &&
            result.senderId_ != global::bnet.protocol.EntityId.DefaultInstance) {
            result.senderId_ = global::bnet.protocol.EntityId.CreateBuilder(result.senderId_).MergeFrom(value).BuildPartial();
        } else {
          result.senderId_ = value;
        }
        result.hasSenderId = true;
        return this;
      }
      public Builder ClearSenderId() {
        result.hasSenderId = false;
        result.senderId_ = global::bnet.protocol.EntityId.DefaultInstance;
        return this;
      }
      
      public bool HasSenderGameAccount {
       get { return result.hasSenderGameAccount; }
      }
      public global::bnet.protocol.EntityId SenderGameAccount {
        get { return result.SenderGameAccount; }
        set { SetSenderGameAccount(value); }
      }
      public Builder SetSenderGameAccount(global::bnet.protocol.EntityId value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        result.hasSenderGameAccount = true;
        result.senderGameAccount_ = value;
        return this;
      }
      public Builder SetSenderGameAccount(global::bnet.protocol.EntityId.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        result.hasSenderGameAccount = true;
        result.senderGameAccount_ = builderForValue.Build();
        return this;
      }
      public Builder MergeSenderGameAccount(global::bnet.protocol.EntityId value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        if (result.hasSenderGameAccount &&
            result.senderGameAccount_ != global::bnet.protocol.EntityId.DefaultInstance) {
            result.senderGameAccount_ = global::bnet.protocol.EntityId.CreateBuilder(result.senderGameAccount_).MergeFrom(value).BuildPartial();
        } else {
          result.senderGameAccount_ = value;
        }
        result.hasSenderGameAccount = true;
        return this;
      }
      public Builder ClearSenderGameAccount() {
        result.hasSenderGameAccount = false;
        result.senderGameAccount_ = global::bnet.protocol.EntityId.DefaultInstance;
        return this;
      }
      
      public bool HasTargetId {
       get { return result.hasTargetId; }
      }
      public global::bnet.protocol.EntityId TargetId {
        get { return result.TargetId; }
        set { SetTargetId(value); }
      }
      public Builder SetTargetId(global::bnet.protocol.EntityId value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        result.hasTargetId = true;
        result.targetId_ = value;
        return this;
      }
      public Builder SetTargetId(global::bnet.protocol.EntityId.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        result.hasTargetId = true;
        result.targetId_ = builderForValue.Build();
        return this;
      }
      public Builder MergeTargetId(global::bnet.protocol.EntityId value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        if (result.hasTargetId &&
            result.targetId_ != global::bnet.protocol.EntityId.DefaultInstance) {
            result.targetId_ = global::bnet.protocol.EntityId.CreateBuilder(result.targetId_).MergeFrom(value).BuildPartial();
        } else {
          result.targetId_ = value;
        }
        result.hasTargetId = true;
        return this;
      }
      public Builder ClearTargetId() {
        result.hasTargetId = false;
        result.targetId_ = global::bnet.protocol.EntityId.DefaultInstance;
        return this;
      }
      
      public bool HasType {
        get { return result.hasType; }
      }
      public string Type {
        get { return result.Type; }
        set { SetType(value); }
      }
      public Builder SetType(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder ClearType() {
        result.hasType = false;
        result.type_ = "";
        return this;
      }
      
      public pbc::IPopsicleList<global::bnet.protocol.attribute.Attribute> AttributeList {
        get { return result.attribute_; }
      }
      public int AttributeCount {
        get { return result.AttributeCount; }
      }
      public global::bnet.protocol.attribute.Attribute GetAttribute(int index) {
        return result.GetAttribute(index);
      }
      public Builder SetAttribute(int index, global::bnet.protocol.attribute.Attribute value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        result.attribute_[index] = value;
        return this;
      }
      public Builder SetAttribute(int index, global::bnet.protocol.attribute.Attribute.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        result.attribute_[index] = builderForValue.Build();
        return this;
      }
      public Builder AddAttribute(global::bnet.protocol.attribute.Attribute value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        result.attribute_.Add(value);
        return this;
      }
      public Builder AddAttribute(global::bnet.protocol.attribute.Attribute.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        result.attribute_.Add(builderForValue.Build());
        return this;
      }
      public Builder AddRangeAttribute(scg::IEnumerable<global::bnet.protocol.attribute.Attribute> values) {
        base.AddRange(values, result.attribute_);
        return this;
      }
      public Builder ClearAttribute() {
        result.attribute_.Clear();
        return this;
      }
    }
    static Notification() {
      object.ReferenceEquals(global::bnet.protocol.notification.Proto.Notification.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
  public sealed partial class FindClientRequest : pb::GeneratedMessage<FindClientRequest, FindClientRequest.Builder> {
    private static readonly FindClientRequest defaultInstance = new Builder().BuildPartial();
    private static readonly string[] _findClientRequestFieldNames = new string[] { "entity_id" };
    private static readonly uint[] _findClientRequestFieldTags = new uint[] { 10 };
    public static FindClientRequest DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override FindClientRequest DefaultInstanceForType {
      get { return defaultInstance; }
    }
    
    protected override FindClientRequest ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::bnet.protocol.notification.Proto.Notification.internal__static_bnet_protocol_notification_FindClientRequest__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<FindClientRequest, FindClientRequest.Builder> InternalFieldAccessors {
      get { return global::bnet.protocol.notification.Proto.Notification.internal__static_bnet_protocol_notification_FindClientRequest__FieldAccessorTable; }
    }
    
    public const int EntityIdFieldNumber = 1;
    private bool hasEntityId;
    private global::bnet.protocol.EntityId entityId_ = global::bnet.protocol.EntityId.DefaultInstance;
    public bool HasEntityId {
      get { return hasEntityId; }
    }
    public global::bnet.protocol.EntityId EntityId {
      get { return entityId_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasEntityId) return false;
        if (!EntityId.IsInitialized) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _findClientRequestFieldNames;
      if (hasEntityId) {
        output.WriteMessage(1, field_names[0], EntityId);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasEntityId) {
          size += pb::CodedOutputStream.ComputeMessageSize(1, EntityId);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static FindClientRequest ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static FindClientRequest ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static FindClientRequest ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static FindClientRequest ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static FindClientRequest ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static FindClientRequest ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static FindClientRequest ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static FindClientRequest ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static FindClientRequest ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static FindClientRequest ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(FindClientRequest prototype) {
      return (Builder) new Builder().MergeFrom(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
    public sealed partial class Builder : pb::GeneratedBuilder<FindClientRequest, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {}
      
      FindClientRequest result = new FindClientRequest();
      
      protected override FindClientRequest MessageBeingBuilt {
        get { return result; }
      }
      
      public override Builder Clear() {
        result = new FindClientRequest();
        return this;
      }
      
      public override Builder Clone() {
        return new Builder().MergeFrom(result);
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::bnet.protocol.notification.FindClientRequest.Descriptor; }
      }
      
      public override FindClientRequest DefaultInstanceForType {
        get { return global::bnet.protocol.notification.FindClientRequest.DefaultInstance; }
      }
      
      public override FindClientRequest BuildPartial() {
        if (result == null) {
          throw new global::System.InvalidOperationException("build() has already been called on this Builder");
        }
        FindClientRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is FindClientRequest) {
          return MergeFrom((FindClientRequest) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(FindClientRequest other) {
        if (other == global::bnet.protocol.notification.FindClientRequest.DefaultInstance) return this;
        if (other.HasEntityId) {
          MergeEntityId(other.EntityId);
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_findClientRequestFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _findClientRequestFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              global::bnet.protocol.EntityId.Builder subBuilder = global::bnet.protocol.EntityId.CreateBuilder();
              if (result.hasEntityId) {
                subBuilder.MergeFrom(EntityId);
              }
              input.ReadMessage(subBuilder, extensionRegistry);
              EntityId = subBuilder.BuildPartial();
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasEntityId {
       get { return result.hasEntityId; }
      }
      public global::bnet.protocol.EntityId EntityId {
        get { return result.EntityId; }
        set { SetEntityId(value); }
      }
      public Builder SetEntityId(global::bnet.protocol.EntityId value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        result.hasEntityId = true;
        result.entityId_ = value;
        return this;
      }
      public Builder SetEntityId(global::bnet.protocol.EntityId.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        result.hasEntityId = true;
        result.entityId_ = builderForValue.Build();
        return this;
      }
      public Builder MergeEntityId(global::bnet.protocol.EntityId value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        if (result.hasEntityId &&
            result.entityId_ != global::bnet.protocol.EntityId.DefaultInstance) {
            result.entityId_ = global::bnet.protocol.EntityId.CreateBuilder(result.entityId_).MergeFrom(value).BuildPartial();
        } else {
          result.entityId_ = value;
        }
        result.hasEntityId = true;
        return this;
      }
      public Builder ClearEntityId() {
        result.hasEntityId = false;
        result.entityId_ = global::bnet.protocol.EntityId.DefaultInstance;
        return this;
      }
    }
    static FindClientRequest() {
      object.ReferenceEquals(global::bnet.protocol.notification.Proto.Notification.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
  public sealed partial class FindClientResponse : pb::GeneratedMessage<FindClientResponse, FindClientResponse.Builder> {
    private static readonly FindClientResponse defaultInstance = new Builder().BuildPartial();
    private static readonly string[] _findClientResponseFieldNames = new string[] { "client_process_id", "label" };
    private static readonly uint[] _findClientResponseFieldTags = new uint[] { 18, 8 };
    public static FindClientResponse DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override FindClientResponse DefaultInstanceForType {
      get { return defaultInstance; }
    }
    
    protected override FindClientResponse ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::bnet.protocol.notification.Proto.Notification.internal__static_bnet_protocol_notification_FindClientResponse__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<FindClientResponse, FindClientResponse.Builder> InternalFieldAccessors {
      get { return global::bnet.protocol.notification.Proto.Notification.internal__static_bnet_protocol_notification_FindClientResponse__FieldAccessorTable; }
    }
    
    public const int LabelFieldNumber = 1;
    private bool hasLabel;
    private uint label_;
    public bool HasLabel {
      get { return hasLabel; }
    }
    public uint Label {
      get { return label_; }
    }
    
    public const int ClientProcessIdFieldNumber = 2;
    private bool hasClientProcessId;
    private global::bnet.protocol.ProcessId clientProcessId_ = global::bnet.protocol.ProcessId.DefaultInstance;
    public bool HasClientProcessId {
      get { return hasClientProcessId; }
    }
    public global::bnet.protocol.ProcessId ClientProcessId {
      get { return clientProcessId_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasLabel) return false;
        if (HasClientProcessId) {
          if (!ClientProcessId.IsInitialized) return false;
        }
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _findClientResponseFieldNames;
      if (hasLabel) {
        output.WriteUInt32(1, field_names[1], Label);
      }
      if (hasClientProcessId) {
        output.WriteMessage(2, field_names[0], ClientProcessId);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasLabel) {
          size += pb::CodedOutputStream.ComputeUInt32Size(1, Label);
        }
        if (hasClientProcessId) {
          size += pb::CodedOutputStream.ComputeMessageSize(2, ClientProcessId);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static FindClientResponse ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static FindClientResponse ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static FindClientResponse ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static FindClientResponse ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static FindClientResponse ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static FindClientResponse ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static FindClientResponse ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static FindClientResponse ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static FindClientResponse ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static FindClientResponse ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(FindClientResponse prototype) {
      return (Builder) new Builder().MergeFrom(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
    public sealed partial class Builder : pb::GeneratedBuilder<FindClientResponse, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {}
      
      FindClientResponse result = new FindClientResponse();
      
      protected override FindClientResponse MessageBeingBuilt {
        get { return result; }
      }
      
      public override Builder Clear() {
        result = new FindClientResponse();
        return this;
      }
      
      public override Builder Clone() {
        return new Builder().MergeFrom(result);
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::bnet.protocol.notification.FindClientResponse.Descriptor; }
      }
      
      public override FindClientResponse DefaultInstanceForType {
        get { return global::bnet.protocol.notification.FindClientResponse.DefaultInstance; }
      }
      
      public override FindClientResponse BuildPartial() {
        if (result == null) {
          throw new global::System.InvalidOperationException("build() has already been called on this Builder");
        }
        FindClientResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is FindClientResponse) {
          return MergeFrom((FindClientResponse) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(FindClientResponse other) {
        if (other == global::bnet.protocol.notification.FindClientResponse.DefaultInstance) return this;
        if (other.HasLabel) {
          Label = other.Label;
        }
        if (other.HasClientProcessId) {
          MergeClientProcessId(other.ClientProcessId);
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_findClientResponseFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _findClientResponseFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 8: {
              result.hasLabel = input.ReadUInt32(ref result.label_);
              break;
            }
            case 18: {
              global::bnet.protocol.ProcessId.Builder subBuilder = global::bnet.protocol.ProcessId.CreateBuilder();
              if (result.hasClientProcessId) {
                subBuilder.MergeFrom(ClientProcessId);
              }
              input.ReadMessage(subBuilder, extensionRegistry);
              ClientProcessId = subBuilder.BuildPartial();
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasLabel {
        get { return result.hasLabel; }
      }
      public uint Label {
        get { return result.Label; }
        set { SetLabel(value); }
      }
      public Builder SetLabel(uint value) {
        result.hasLabel = true;
        result.label_ = value;
        return this;
      }
      public Builder ClearLabel() {
        result.hasLabel = false;
        result.label_ = 0;
        return this;
      }
      
      public bool HasClientProcessId {
       get { return result.hasClientProcessId; }
      }
      public global::bnet.protocol.ProcessId ClientProcessId {
        get { return result.ClientProcessId; }
        set { SetClientProcessId(value); }
      }
      public Builder SetClientProcessId(global::bnet.protocol.ProcessId value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        result.hasClientProcessId = true;
        result.clientProcessId_ = value;
        return this;
      }
      public Builder SetClientProcessId(global::bnet.protocol.ProcessId.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        result.hasClientProcessId = true;
        result.clientProcessId_ = builderForValue.Build();
        return this;
      }
      public Builder MergeClientProcessId(global::bnet.protocol.ProcessId value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        if (result.hasClientProcessId &&
            result.clientProcessId_ != global::bnet.protocol.ProcessId.DefaultInstance) {
            result.clientProcessId_ = global::bnet.protocol.ProcessId.CreateBuilder(result.clientProcessId_).MergeFrom(value).BuildPartial();
        } else {
          result.clientProcessId_ = value;
        }
        result.hasClientProcessId = true;
        return this;
      }
      public Builder ClearClientProcessId() {
        result.hasClientProcessId = false;
        result.clientProcessId_ = global::bnet.protocol.ProcessId.DefaultInstance;
        return this;
      }
    }
    static FindClientResponse() {
      object.ReferenceEquals(global::bnet.protocol.notification.Proto.Notification.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
  public sealed partial class RegisterClientRequest : pb::GeneratedMessage<RegisterClientRequest, RegisterClientRequest.Builder> {
    private static readonly RegisterClientRequest defaultInstance = new Builder().BuildPartial();
    private static readonly string[] _registerClientRequestFieldNames = new string[] { "entity_id" };
    private static readonly uint[] _registerClientRequestFieldTags = new uint[] { 10 };
    public static RegisterClientRequest DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override RegisterClientRequest DefaultInstanceForType {
      get { return defaultInstance; }
    }
    
    protected override RegisterClientRequest ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::bnet.protocol.notification.Proto.Notification.internal__static_bnet_protocol_notification_RegisterClientRequest__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<RegisterClientRequest, RegisterClientRequest.Builder> InternalFieldAccessors {
      get { return global::bnet.protocol.notification.Proto.Notification.internal__static_bnet_protocol_notification_RegisterClientRequest__FieldAccessorTable; }
    }
    
    public const int EntityIdFieldNumber = 1;
    private bool hasEntityId;
    private global::bnet.protocol.EntityId entityId_ = global::bnet.protocol.EntityId.DefaultInstance;
    public bool HasEntityId {
      get { return hasEntityId; }
    }
    public global::bnet.protocol.EntityId EntityId {
      get { return entityId_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasEntityId) return false;
        if (!EntityId.IsInitialized) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _registerClientRequestFieldNames;
      if (hasEntityId) {
        output.WriteMessage(1, field_names[0], EntityId);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasEntityId) {
          size += pb::CodedOutputStream.ComputeMessageSize(1, EntityId);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static RegisterClientRequest ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static RegisterClientRequest ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static RegisterClientRequest ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static RegisterClientRequest ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static RegisterClientRequest ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static RegisterClientRequest ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static RegisterClientRequest ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static RegisterClientRequest ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static RegisterClientRequest ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static RegisterClientRequest ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(RegisterClientRequest prototype) {
      return (Builder) new Builder().MergeFrom(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
    public sealed partial class Builder : pb::GeneratedBuilder<RegisterClientRequest, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {}
      
      RegisterClientRequest result = new RegisterClientRequest();
      
      protected override RegisterClientRequest MessageBeingBuilt {
        get { return result; }
      }
      
      public override Builder Clear() {
        result = new RegisterClientRequest();
        return this;
      }
      
      public override Builder Clone() {
        return new Builder().MergeFrom(result);
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::bnet.protocol.notification.RegisterClientRequest.Descriptor; }
      }
      
      public override RegisterClientRequest DefaultInstanceForType {
        get { return global::bnet.protocol.notification.RegisterClientRequest.DefaultInstance; }
      }
      
      public override RegisterClientRequest BuildPartial() {
        if (result == null) {
          throw new global::System.InvalidOperationException("build() has already been called on this Builder");
        }
        RegisterClientRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is RegisterClientRequest) {
          return MergeFrom((RegisterClientRequest) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(RegisterClientRequest other) {
        if (other == global::bnet.protocol.notification.RegisterClientRequest.DefaultInstance) return this;
        if (other.HasEntityId) {
          MergeEntityId(other.EntityId);
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_registerClientRequestFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _registerClientRequestFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              global::bnet.protocol.EntityId.Builder subBuilder = global::bnet.protocol.EntityId.CreateBuilder();
              if (result.hasEntityId) {
                subBuilder.MergeFrom(EntityId);
              }
              input.ReadMessage(subBuilder, extensionRegistry);
              EntityId = subBuilder.BuildPartial();
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasEntityId {
       get { return result.hasEntityId; }
      }
      public global::bnet.protocol.EntityId EntityId {
        get { return result.EntityId; }
        set { SetEntityId(value); }
      }
      public Builder SetEntityId(global::bnet.protocol.EntityId value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        result.hasEntityId = true;
        result.entityId_ = value;
        return this;
      }
      public Builder SetEntityId(global::bnet.protocol.EntityId.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        result.hasEntityId = true;
        result.entityId_ = builderForValue.Build();
        return this;
      }
      public Builder MergeEntityId(global::bnet.protocol.EntityId value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        if (result.hasEntityId &&
            result.entityId_ != global::bnet.protocol.EntityId.DefaultInstance) {
            result.entityId_ = global::bnet.protocol.EntityId.CreateBuilder(result.entityId_).MergeFrom(value).BuildPartial();
        } else {
          result.entityId_ = value;
        }
        result.hasEntityId = true;
        return this;
      }
      public Builder ClearEntityId() {
        result.hasEntityId = false;
        result.entityId_ = global::bnet.protocol.EntityId.DefaultInstance;
        return this;
      }
    }
    static RegisterClientRequest() {
      object.ReferenceEquals(global::bnet.protocol.notification.Proto.Notification.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
  public sealed partial class UnregisterClientRequest : pb::GeneratedMessage<UnregisterClientRequest, UnregisterClientRequest.Builder> {
    private static readonly UnregisterClientRequest defaultInstance = new Builder().BuildPartial();
    private static readonly string[] _unregisterClientRequestFieldNames = new string[] { "entity_id" };
    private static readonly uint[] _unregisterClientRequestFieldTags = new uint[] { 10 };
    public static UnregisterClientRequest DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override UnregisterClientRequest DefaultInstanceForType {
      get { return defaultInstance; }
    }
    
    protected override UnregisterClientRequest ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::bnet.protocol.notification.Proto.Notification.internal__static_bnet_protocol_notification_UnregisterClientRequest__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<UnregisterClientRequest, UnregisterClientRequest.Builder> InternalFieldAccessors {
      get { return global::bnet.protocol.notification.Proto.Notification.internal__static_bnet_protocol_notification_UnregisterClientRequest__FieldAccessorTable; }
    }
    
    public const int EntityIdFieldNumber = 1;
    private bool hasEntityId;
    private global::bnet.protocol.EntityId entityId_ = global::bnet.protocol.EntityId.DefaultInstance;
    public bool HasEntityId {
      get { return hasEntityId; }
    }
    public global::bnet.protocol.EntityId EntityId {
      get { return entityId_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasEntityId) return false;
        if (!EntityId.IsInitialized) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _unregisterClientRequestFieldNames;
      if (hasEntityId) {
        output.WriteMessage(1, field_names[0], EntityId);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasEntityId) {
          size += pb::CodedOutputStream.ComputeMessageSize(1, EntityId);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static UnregisterClientRequest ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static UnregisterClientRequest ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static UnregisterClientRequest ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static UnregisterClientRequest ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static UnregisterClientRequest ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static UnregisterClientRequest ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static UnregisterClientRequest ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static UnregisterClientRequest ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static UnregisterClientRequest ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static UnregisterClientRequest ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(UnregisterClientRequest prototype) {
      return (Builder) new Builder().MergeFrom(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
    public sealed partial class Builder : pb::GeneratedBuilder<UnregisterClientRequest, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {}
      
      UnregisterClientRequest result = new UnregisterClientRequest();
      
      protected override UnregisterClientRequest MessageBeingBuilt {
        get { return result; }
      }
      
      public override Builder Clear() {
        result = new UnregisterClientRequest();
        return this;
      }
      
      public override Builder Clone() {
        return new Builder().MergeFrom(result);
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::bnet.protocol.notification.UnregisterClientRequest.Descriptor; }
      }
      
      public override UnregisterClientRequest DefaultInstanceForType {
        get { return global::bnet.protocol.notification.UnregisterClientRequest.DefaultInstance; }
      }
      
      public override UnregisterClientRequest BuildPartial() {
        if (result == null) {
          throw new global::System.InvalidOperationException("build() has already been called on this Builder");
        }
        UnregisterClientRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is UnregisterClientRequest) {
          return MergeFrom((UnregisterClientRequest) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(UnregisterClientRequest other) {
        if (other == global::bnet.protocol.notification.UnregisterClientRequest.DefaultInstance) return this;
        if (other.HasEntityId) {
          MergeEntityId(other.EntityId);
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_unregisterClientRequestFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _unregisterClientRequestFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              global::bnet.protocol.EntityId.Builder subBuilder = global::bnet.protocol.EntityId.CreateBuilder();
              if (result.hasEntityId) {
                subBuilder.MergeFrom(EntityId);
              }
              input.ReadMessage(subBuilder, extensionRegistry);
              EntityId = subBuilder.BuildPartial();
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasEntityId {
       get { return result.hasEntityId; }
      }
      public global::bnet.protocol.EntityId EntityId {
        get { return result.EntityId; }
        set { SetEntityId(value); }
      }
      public Builder SetEntityId(global::bnet.protocol.EntityId value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        result.hasEntityId = true;
        result.entityId_ = value;
        return this;
      }
      public Builder SetEntityId(global::bnet.protocol.EntityId.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        result.hasEntityId = true;
        result.entityId_ = builderForValue.Build();
        return this;
      }
      public Builder MergeEntityId(global::bnet.protocol.EntityId value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        if (result.hasEntityId &&
            result.entityId_ != global::bnet.protocol.EntityId.DefaultInstance) {
            result.entityId_ = global::bnet.protocol.EntityId.CreateBuilder(result.entityId_).MergeFrom(value).BuildPartial();
        } else {
          result.entityId_ = value;
        }
        result.hasEntityId = true;
        return this;
      }
      public Builder ClearEntityId() {
        result.hasEntityId = false;
        result.entityId_ = global::bnet.protocol.EntityId.DefaultInstance;
        return this;
      }
    }
    static UnregisterClientRequest() {
      object.ReferenceEquals(global::bnet.protocol.notification.Proto.Notification.Descriptor, null);
    }
  }
  
  #endregion
  
  #region Services
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
  public abstract class NotificationService : pb::IService {
    public abstract void SendNotification(
        pb::IRpcController controller,
        global::bnet.protocol.notification.Notification request,
        global::System.Action<global::bnet.protocol.NoData> done);
    public abstract void RegisterClient(
        pb::IRpcController controller,
        global::bnet.protocol.notification.RegisterClientRequest request,
        global::System.Action<global::bnet.protocol.NoData> done);
    public abstract void UnregisterClient(
        pb::IRpcController controller,
        global::bnet.protocol.notification.UnregisterClientRequest request,
        global::System.Action<global::bnet.protocol.NoData> done);
    public abstract void FindClient(
        pb::IRpcController controller,
        global::bnet.protocol.notification.FindClientRequest request,
        global::System.Action<global::bnet.protocol.notification.FindClientResponse> done);
    
    public static pbd::ServiceDescriptor Descriptor {
      get { return Proto.Notification.Descriptor.Services[0]; }
    }
    public pbd::ServiceDescriptor DescriptorForType {
      get { return Descriptor; }
    }
    
    public void CallMethod(
        pbd::MethodDescriptor method,
        pb::IRpcController controller,
        pb::IMessage request,
        global::System.Action<pb::IMessage> done) {
      if (method.Service != Descriptor) {
        throw new global::System.ArgumentException(
            "Service.CallMethod() given method descriptor for wrong service type.");
      }
      switch(method.Index) {
        case 0:
          this.SendNotification(controller, (global::bnet.protocol.notification.Notification) request,
              pb::RpcUtil.SpecializeCallback<global::bnet.protocol.NoData>(
              done));
          return;
        case 1:
          this.RegisterClient(controller, (global::bnet.protocol.notification.RegisterClientRequest) request,
              pb::RpcUtil.SpecializeCallback<global::bnet.protocol.NoData>(
              done));
          return;
        case 2:
          this.UnregisterClient(controller, (global::bnet.protocol.notification.UnregisterClientRequest) request,
              pb::RpcUtil.SpecializeCallback<global::bnet.protocol.NoData>(
              done));
          return;
        case 3:
          this.FindClient(controller, (global::bnet.protocol.notification.FindClientRequest) request,
              pb::RpcUtil.SpecializeCallback<global::bnet.protocol.notification.FindClientResponse>(
              done));
          return;
        default:
          throw new global::System.InvalidOperationException("Can't get here.");
      }
    }
    
    public pb::IMessage GetRequestPrototype(pbd::MethodDescriptor method) {
      if (method.Service != Descriptor) {
        throw new global::System.ArgumentException(
            "Service.GetRequestPrototype() given method descriptor for wrong service type.");
      }
      switch(method.Index) {
        case 0:
          return global::bnet.protocol.notification.Notification.DefaultInstance;
        case 1:
          return global::bnet.protocol.notification.RegisterClientRequest.DefaultInstance;
        case 2:
          return global::bnet.protocol.notification.UnregisterClientRequest.DefaultInstance;
        case 3:
          return global::bnet.protocol.notification.FindClientRequest.DefaultInstance;
        default:
          throw new global::System.InvalidOperationException("Can't get here.");
      }
    }
    
    public pb::IMessage GetResponsePrototype(pbd::MethodDescriptor method) {
      if (method.Service != Descriptor) {
        throw new global::System.ArgumentException(
            "Service.GetResponsePrototype() given method descriptor for wrong service type.");
      }
      switch(method.Index) {
        case 0:
          return global::bnet.protocol.NoData.DefaultInstance;
        case 1:
          return global::bnet.protocol.NoData.DefaultInstance;
        case 2:
          return global::bnet.protocol.NoData.DefaultInstance;
        case 3:
          return global::bnet.protocol.notification.FindClientResponse.DefaultInstance;
        default:
          throw new global::System.InvalidOperationException("Can't get here.");
      }
    }
    
    public static Stub CreateStub(pb::IRpcChannel channel) {
      return new Stub(channel);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
    public class Stub : global::bnet.protocol.notification.NotificationService {
      internal Stub(pb::IRpcChannel channel) {
        this.channel = channel;
      }
      
      private readonly pb::IRpcChannel channel;
      
      public pb::IRpcChannel Channel {
        get { return channel; }
      }
      
      public override void SendNotification(
          pb::IRpcController controller,
          global::bnet.protocol.notification.Notification request,
          global::System.Action<global::bnet.protocol.NoData> done) {
        channel.CallMethod(Descriptor.Methods[0],
            controller, request, global::bnet.protocol.NoData.DefaultInstance,
            pb::RpcUtil.GeneralizeCallback<global::bnet.protocol.NoData, global::bnet.protocol.NoData.Builder>(done, global::bnet.protocol.NoData.DefaultInstance));
      }
      
      public override void RegisterClient(
          pb::IRpcController controller,
          global::bnet.protocol.notification.RegisterClientRequest request,
          global::System.Action<global::bnet.protocol.NoData> done) {
        channel.CallMethod(Descriptor.Methods[1],
            controller, request, global::bnet.protocol.NoData.DefaultInstance,
            pb::RpcUtil.GeneralizeCallback<global::bnet.protocol.NoData, global::bnet.protocol.NoData.Builder>(done, global::bnet.protocol.NoData.DefaultInstance));
      }
      
      public override void UnregisterClient(
          pb::IRpcController controller,
          global::bnet.protocol.notification.UnregisterClientRequest request,
          global::System.Action<global::bnet.protocol.NoData> done) {
        channel.CallMethod(Descriptor.Methods[2],
            controller, request, global::bnet.protocol.NoData.DefaultInstance,
            pb::RpcUtil.GeneralizeCallback<global::bnet.protocol.NoData, global::bnet.protocol.NoData.Builder>(done, global::bnet.protocol.NoData.DefaultInstance));
      }
      
      public override void FindClient(
          pb::IRpcController controller,
          global::bnet.protocol.notification.FindClientRequest request,
          global::System.Action<global::bnet.protocol.notification.FindClientResponse> done) {
        channel.CallMethod(Descriptor.Methods[3],
            controller, request, global::bnet.protocol.notification.FindClientResponse.DefaultInstance,
            pb::RpcUtil.GeneralizeCallback<global::bnet.protocol.notification.FindClientResponse, global::bnet.protocol.notification.FindClientResponse.Builder>(done, global::bnet.protocol.notification.FindClientResponse.DefaultInstance));
      }
    }
  }
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
  public abstract class NotificationListener : pb::IService {
    public abstract void OnNotificationReceived(
        pb::IRpcController controller,
        global::bnet.protocol.notification.Notification request,
        global::System.Action<global::bnet.protocol.NO_RESPONSE> done);
    
    public static pbd::ServiceDescriptor Descriptor {
      get { return Proto.Notification.Descriptor.Services[1]; }
    }
    public pbd::ServiceDescriptor DescriptorForType {
      get { return Descriptor; }
    }
    
    public void CallMethod(
        pbd::MethodDescriptor method,
        pb::IRpcController controller,
        pb::IMessage request,
        global::System.Action<pb::IMessage> done) {
      if (method.Service != Descriptor) {
        throw new global::System.ArgumentException(
            "Service.CallMethod() given method descriptor for wrong service type.");
      }
      switch(method.Index) {
        case 0:
          this.OnNotificationReceived(controller, (global::bnet.protocol.notification.Notification) request,
              pb::RpcUtil.SpecializeCallback<global::bnet.protocol.NO_RESPONSE>(
              done));
          return;
        default:
          throw new global::System.InvalidOperationException("Can't get here.");
      }
    }
    
    public pb::IMessage GetRequestPrototype(pbd::MethodDescriptor method) {
      if (method.Service != Descriptor) {
        throw new global::System.ArgumentException(
            "Service.GetRequestPrototype() given method descriptor for wrong service type.");
      }
      switch(method.Index) {
        case 0:
          return global::bnet.protocol.notification.Notification.DefaultInstance;
        default:
          throw new global::System.InvalidOperationException("Can't get here.");
      }
    }
    
    public pb::IMessage GetResponsePrototype(pbd::MethodDescriptor method) {
      if (method.Service != Descriptor) {
        throw new global::System.ArgumentException(
            "Service.GetResponsePrototype() given method descriptor for wrong service type.");
      }
      switch(method.Index) {
        case 0:
          return global::bnet.protocol.NO_RESPONSE.DefaultInstance;
        default:
          throw new global::System.InvalidOperationException("Can't get here.");
      }
    }
    
    public static Stub CreateStub(pb::IRpcChannel channel) {
      return new Stub(channel);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
    public class Stub : global::bnet.protocol.notification.NotificationListener {
      internal Stub(pb::IRpcChannel channel) {
        this.channel = channel;
      }
      
      private readonly pb::IRpcChannel channel;
      
      public pb::IRpcChannel Channel {
        get { return channel; }
      }
      
      public override void OnNotificationReceived(
          pb::IRpcController controller,
          global::bnet.protocol.notification.Notification request,
          global::System.Action<global::bnet.protocol.NO_RESPONSE> done) {
        channel.CallMethod(Descriptor.Methods[0],
            controller, request, global::bnet.protocol.NO_RESPONSE.DefaultInstance,
            pb::RpcUtil.GeneralizeCallback<global::bnet.protocol.NO_RESPONSE, global::bnet.protocol.NO_RESPONSE.Builder>(done, global::bnet.protocol.NO_RESPONSE.DefaultInstance));
      }
    }
  }
  #endregion
  
}

#endregion Designer generated code
